services:
  app:
    image: secure-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/app/app", "-health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

